# NOTE: all relative paths are to the directory of the script being called

# where the images are stored on the camera
# see `gphoto2 --list-files` for both
CAMERA_ROOT_PATH = "/store_00010001"
CAMERA_IMAGE_PATH = "/DCIM/102NZ_50"
camera_path = CAMERA_ROOT_PATH + CAMERA_IMAGE_PATH

# path to Arduino's serial port
ARDUINO_PATH = "/dev/ttyACM0"

# the path to the Metashape license file
METASHAPE_KEY_DIRECTORY_PATH = "/home/xiaoxiae/Downloads/metashape-pro"

# the resolution of the texture file
TEXTURE_RESOLUTION = 1024

# a marker id:position dictionary (in meters):
#
#                 z+
#                 |
#                 o-- y+
#                /
#               x+
#
# the origin of the hold should be at (0, 0, 0)
MARKERS = {
    94: (-0.0633, -0.0695, 0),
    91: (0.1087, -0.0695, 0),
    92: (0.0217, 0.0869, 0),
}

# the possible named colors of the holds that are used when determining their color
# generated by picking certain colors from matplotlib:
# > import matplotlib
# > for cname, hex in matplotlib.colors.cnames.items():
# >     print(cname,hex)
NAMED_COLORS = {
    "azure": "#F0FFFF",
    "beige": "#F5F5DC",
    "black": "#000000",
    "blue": "#0000FF",
    "brown": "#A52A2A",
    "cyan": "#00FFFF",
    "darkblue": "#00008B",
    "darkgreen": "#006400",
    "darkred": "#8B0000",
    "fuchsia": "#FF00FF",
    "gold": "#FFD700",
    "gray": "#808080",
    "green": "#008000",
    "grey": "#808080",
    "lightblue": "#ADD8E6",
    "lightgreen": "#90EE90",
    "lime": "#00FF00",
    "magenta": "#FF00FF",
    "orange": "#FFA500",
    "pink": "#FFC0CB",
    "purple": "#800080",
    "red": "#FF0000",
    "salmon": "#FA8072",
    "violet": "#EE82EE",
    "white": "#FFFFFF",
    "yellow": "#FFFF00",
}


# -- DO NOT CHANGE ANYTHING BELLOW -- #

# the extension of the images
IMAGE_EXTENSION = "nef"

# folder where the scans of the holds are saved
SCAN_PATH = "scans"

# folders where the generated models are stored (and what each of their names are)
MODEL_PATH = "models"
MODEL_FILE_NAME = "model"

# the name of the file containing all the hold information
MODEL_YAML_NAME = "holds.yaml"
